// src/components/website/pages/ContactForm.jsx
import { useEffect, useRef, useState } from "react"
import { gsap } from "gsap"
import { ScrollTrigger } from "gsap/ScrollTrigger"

const ContactForm = () => {
  const formRef = useRef(null)
  const [formData, setFormData] = useState({
    company: "",
    firstName: "",
    lastName: "",
    email: "",
    message: "",
  })

  const maxMessageLength = 800 // Maximum character limit for the message

  const email = import.meta.env.VITE_FORM_EMAIL // Ensure you have this in your .env file

  const [errors, setErrors] = useState({})
  const [submitting, setSubmitting] = useState(false)
  const [showThankYou, setShowThankYou] = useState(false)

  const handleChange = (e) => {
    const { name, value } = e.target
    setFormData((prev) => ({
      ...prev,
      [name]: value,
    }))
  }

  const validateForm = () => {
    const newErrors = {}

    if (!formData.firstName.trim())
      newErrors.firstName = "First name is required"
    if (!formData.lastName.trim()) newErrors.lastName = "Last name is required"
    if (!formData.message.trim()) newErrors.message = "Message is required"

    // Basic email format check
    const emailRegex = /^[^\s@]+@[^\s@]+\.[^\s@]+$/
    if (!formData.email.trim()) {
      newErrors.email = "Email is required"
    } else if (!emailRegex.test(formData.email.trim())) {
      newErrors.email = "Invalid email format"
    }

    // Optional: Block suspicious TLDs or domains
    const spammyPatterns = ["@tempmail", "@10minutemail", "@mailinator"]
    if (
      spammyPatterns.some((pattern) =>
        formData.email.toLowerCase().includes(pattern)
      )
    ) {
      newErrors.email = "Please use a real email address"
    }

    setErrors(newErrors)
    return Object.keys(newErrors).length === 0
  }

  const handleSubmit = async (e) => {
    e.preventDefault()
    setSubmitting(true)

    if (!validateForm()) {
      setSubmitting(false)
      return
    }

    const payload = new FormData()
    Object.entries(formData).forEach(([key, value]) => {
      payload.append(key, value)
    })

    // FormSubmit required hidden fields
    payload.append("_template", "table")
    payload.append("_subject", "New Contact Submission")
    payload.append("_captcha", "false")

    try {
      //import VIte Email from env
      const response = await fetch(email, {
        method: "POST",
        body: payload,
      })

      if (response.ok) {
        setShowThankYou(true)
        setFormData({
          company: "",
          firstName: "",
          lastName: "",
          email: "",
          message: "",
        })
        setErrors({})
      } else {
        alert("There was a problem submitting the form.")
      }
    } catch (error) {
      console.error("Error submitting the form:", error)
    } finally {
      setSubmitting(false)
    }
  }

  gsap.registerPlugin(ScrollTrigger)

  useEffect(() => {
    const heading = document.querySelector(".heading")
    const subheading = document.querySelector(".subheading")
    const button = document.querySelector(".btn-animate")

    if (heading) {
      gsap.fromTo(
        heading,
        { opacity: 0, y: -150 },
        {
          opacity: 1,
          y: 0,
          duration: 1,
          ease: "power1.in",
          scrollTrigger: {
            trigger: heading,
            start: "top 80%",
            toggleActions: "play none none none", // Only plays once
          },
        }
      )
    }

    if (subheading) {
      gsap.fromTo(
        subheading,
        { opacity: 0, x: -150 },
        {
          opacity: 1,
          x: 0,
          duration: 1,
          ease: "power2.in",
          delay: 0.5,
          scrollTrigger: {
            trigger: subheading,
            start: "top 80%",
            toggleActions: "play none none none", // Only plays once
          },
        }
      )
      if (button) {
        button.addEventListener("mouseenter", () => {
          gsap.fromTo(
            button,
            { scale: 1 },
            {
              scale: 1.08,
              duration: 0.2,
              ease: "power1.out",
              yoyo: true,
              repeat: 1,
            }
          )
        })
      }
    }
  }, [])

  if (document.querySelector(".btn-animate")) {
    gsap.fromTo(
      ".btn-animate",
      {
        opacity: 0,
        y: 50,
      },
      {
        opacity: 1,
        y: 0,
        duration: 1,
        ease: "power2.in",
        scrollTrigger: {
          trigger: ".btn-animate",
          start: "top 80%",
          toggleActions: "play none none none",
        },
      }
    )
  }

  return (
    <>
      <svg
        className="block w-full h-auto -mt-2"
        viewBox="0 280 900 300"
        preserveAspectRatio="none"
        xmlns="http://www.w3.org/2000/svg"
      >
        {/* Layer 1 */}
        <path fill="#1a46a4">
          <animate
            attributeName="d"
            dur="10s"
            repeatCount="indefinite"
            values="
        M0,400 C150,350 300,450 450,400 C600,350 750,450 900,400 L900,600 L0,600Z;
        M0,420 C150,380 300,460 450,420 C600,380 750,460 900,420 L900,600 L0,600Z;
        M0,400 C150,350 300,450 450,400 C600,350 750,450 900,400 L900,600 L0,600Z"
          />
        </path>

        {/* Layer 2 */}
        <path fill="#225ad3" opacity="0.6">
          <animate
            attributeName="d"
            dur="12s"
            repeatCount="indefinite"
            values="
        M0,420 C200,370 400,470 600,420 C800,370 1000,470 1200,420 L1200,600 L0,600Z;
        M0,430 C200,390 400,490 600,430 C800,390 1000,490 1200,430 L1200,600 L0,600Z;
        M0,420 C200,370 400,470 600,420 C800,370 1000,470 1200,420 L1200,600 L0,600Z"
          />
        </path>

        {/* Layer 3 */}
        <path fill="#2664eb" opacity="0.4">
          <animate
            attributeName="d"
            dur="14s"
            repeatCount="indefinite"
            values="
        M0,440 C250,390 500,510 750,440 C1000,390 1250,510 1500,440 L1500,600 L0,600Z;
        M0,450 C250,410 500,520 750,450 C1000,410 1250,520 1500,450 L1500,600 L0,600Z;
        M0,440 C250,390 500,510 750,440 C1000,390 1250,510 1500,440 L1500,600 L0,600Z"
          />
        </path>

        {/* Layer 4 */}
        <path fill="#2664eb" opacity="1">
          <animate
            attributeName="d"
            dur="16s"
            repeatCount="indefinite"
            values="
        M0,460 C300,410 600,530 900,460 C1200,410 1500,530 1800,460 L1800,600 L0,600Z;
        M0,470 C300,430 600,540 900,470 C1200,430 1500,540 1800,470 L1800,600 L0,600Z;
        M0,460 C300,410 600,530 900,460 C1200,410 1500,530 1800,460 L1800,600 L0,600Z"
          />
        </path>
      </svg>
      <div className="flex flex-col items-center justify-center gap-4 bg-blue-600">
        <h1 className="flex p-4 text-4xl font-bold text-center heading md:text-6xl text-shadow-md text-slate-50">
          Have a Question or a Project in Mind?
        </h1>
        <p className="flex justify-center max-w-sm p-5 text-xl text-center subheading md:max-w-screen-lg w-fit text-slate-100">
          We&apos;d love to hear from you! Whether you&apos;re ready to kick off
          a new project, need support, or just want to say hi—drop us a message
          and we&apos;ll get back to you soon.
        </p>
      </div>
      <div
        id="contact-form"
        className="flex justify-center w-full p-4 md:p-20 bg-gradient-to-b from-blue-600 to-blue-950"
      >
        <form
          ref={formRef}
          action="https://formsubmit.co/49b3ec7186e27ea9fd61c9e9f858330c"
          method="POST"
          onSubmit={handleSubmit}
          className="w-full p-6 mb-6 space-y-6 rounded-lg shadow-lg md:p-6 md:max-w-screen-md bg-slate-50 md:px-10"
        >
          {/* Hidden FormSubmit inputs */}
          <input type="hidden" name="_template" value="table" />
          <input type="hidden" name="_subject" value="New Contact Submission" />
          <input type="hidden" name="_captcha" value="false" />
          <input type="text" name="_honey" style={{ display: "none" }} />
          <input
            type="hidden"
            name="_next"
            value="http://localhost:5174/"
          ></input>

          {/* Company */}
          <div>
            <label
              htmlFor="company"
              className="block text-sm font-medium select-none text-sky-950"
            >
              Company (Optional)
            </label>
            <input
              type="text"
              id="company"
              name="company"
              value={formData.company}
              onChange={handleChange}
              className="block w-full p-3 mt-1 transition duration-150 ease-in-out border border-gray-300 rounded-md focus:border-blue-500 focus:ring-blue-500"
              placeholder="Business Name"
            />
          </div>

          {/* First Name */}
          <div>
            <label
              htmlFor="firstName"
              className="block text-sm font-medium select-none text-sky-950"
            >
              First Name <span className="text-red-500">*</span>
            </label>
            <input
              type="text"
              id="firstName"
              name="firstName"
              value={formData.firstName}
              onChange={handleChange}
              className="block w-full p-3 mt-1 transition duration-150 ease-in-out border border-gray-300 rounded-md focus:border-blue-500 focus:ring-blue-500"
              placeholder="First Name"
            />
            {errors.firstName && (
              <p className="mt-1 text-sm text-red-500">{errors.firstName}</p>
            )}
          </div>

          {/* Last Name */}
          <div>
            <label
              htmlFor="lastName"
              className="block text-sm font-medium select-none text-sky-950"
            >
              Last Name <span className="text-red-500">*</span>
            </label>
            <input
              type="text"
              id="lastName"
              name="lastName"
              value={formData.lastName}
              onChange={handleChange}
              className="block w-full p-3 mt-1 transition duration-150 ease-in-out border border-gray-300 rounded-md focus:border-blue-500 focus:ring-blue-500"
              placeholder="Last Name"
            />
            {errors.lastName && (
              <p className="mt-1 text-sm text-red-500">{errors.lastName}</p>
            )}
          </div>

          {/* Email */}
          <div>
            <label
              htmlFor="lastName"
              className="block text-sm font-medium select-none text-sky-950"
            >
              Email <span className="text-red-500">*</span>
            </label>
            <input
              type="text"
              id="email"
              name="email"
              value={formData.email}
              onChange={handleChange}
              className="block w-full p-3 mt-1 transition duration-150 ease-in-out border border-gray-300 rounded-md focus:border-blue-500 focus:ring-blue-500"
              placeholder="Email"
            />
            {errors.email && (
              <p className="mt-1 text-sm text-red-500">{errors.email}</p>
            )}
          </div>

          {/* Message */}
          <div>
            <label
              htmlFor="message"
              className="block text-sm font-medium select-none text-sky-950"
            >
              Message <span className="text-red-500">*</span>
            </label>
            <textarea
              id="message"
              name="message"
              value={formData.message}
              onChange={handleChange}
              className="block w-full p-3 mt-1 transition duration-150 ease-in-out border border-gray-300 rounded-md focus:border-blue-500 focus:ring-blue-500"
              rows="4"
              placeholder="Message"
              maxLength={maxMessageLength} // <-- Character limit
            ></textarea>
            <div
              className={`text-sm text-right ${
                formData.message.length >= maxMessageLength
                  ? "text-red-800"
                  : formData.message.length >= maxMessageLength - 20
                  ? "text-orange-600"
                  : "text-slate-400"
              }`}
            >
              {formData.message.length}/{maxMessageLength} characters
            </div>

            {errors.message && (
              <p className="mt-1 text-sm text-red-500">{errors.message}</p>
            )}
          </div>

          <button
            type="submit"
            disabled={submitting}
            className="w-full px-6 py-3 text-lg font-semibold text-white transition-all duration-300 ease-in-out rounded-full btn-animate bg-gradient-to-br from-zinc-800 to-zinc-900 "
          >
            {submitting ? "Submitting..." : "Submit"}
          </button>
        </form>
      </div>

      {/* Thank You Modal */}
      {showThankYou && (
        <div className="fixed inset-0 z-50 flex items-center justify-center bg-black bg-opacity-50">
          <div className="max-w-sm p-8 text-center bg-white rounded-lg shadow-lg">
            <h2 className="mb-4 text-2xl font-bold text-green-600">
              Thank You!
            </h2>
            <p className="text-gray-700">
              Your message has been submitted successfully.
            </p>
            <button
              onClick={() => setShowThankYou(false)}
              className="px-4 py-2 mt-6 text-white bg-blue-600 rounded hover:bg-blue-700"
            >
              Close
            </button>
          </div>
        </div>
      )}
    </>
  )
}

export default ContactForm

// src/app/components/pages/ContactForm.vue
<script setup>
import { ref, reactive, computed, onMounted, onBeforeUnmount } from "vue"
import gsap from "gsap"
import ScrollTrigger from "gsap/ScrollTrigger"

gsap.registerPlugin(ScrollTrigger)

/* ------------------------
   ENV
------------------------ */
const emailEndpoint = import.meta.env.VITE_FORM_EMAIL

/* ------------------------
   STATE
------------------------ */
const formRef = ref(null)

const formData = reactive({
  company: "",
  firstName: "",
  lastName: "",
  email: "",
  message: "",
})

const errors = reactive({})
const submitting = ref(false)
const showThankYou = ref(false)

const maxMessageLength = 800

/* ------------------------
   COMPUTED
------------------------ */
const messageLengthClass = computed(() => {
  const len = formData.message.length
  if (len >= maxMessageLength) return "text-red-800"
  if (len >= maxMessageLength - 20) return "text-orange-600"
  return "text-slate-600 font-semibold"
})

/* ------------------------
   VALIDATION
------------------------ */
const validateForm = () => {
  Object.keys(errors).forEach((k) => delete errors[k])

  if (!formData.firstName.trim()) errors.firstName = "First name is required"
  if (!formData.lastName.trim()) errors.lastName = "Last name is required"
  if (!formData.message.trim()) errors.message = "Message is required"

  const emailRegex = /^[^\s@]+@[^\s@]+\.[^\s@]+$/
  if (!formData.email.trim()) {
    errors.email = "Email is required"
  } else if (!emailRegex.test(formData.email.trim())) {
    errors.email = "Invalid email format"
  }

  const spammyPatterns = ["@tempmail", "@10minutemail", "@mailinator"]
  if (spammyPatterns.some((p) => formData.email.toLowerCase().includes(p))) {
    errors.email = "Please use a real email address"
  }

  return Object.keys(errors).length === 0
}

/* ------------------------
   SUBMIT
------------------------ */
const handleSubmit = async () => {
  submitting.value = true

  if (!validateForm()) {
    submitting.value = false
    return
  }

  const payload = new FormData()
  Object.entries(formData).forEach(([key, value]) => {
    payload.append(key, value)
  })

  payload.append("_template", "table")
  payload.append("_subject", "New Contact Submission")
  payload.append("_captcha", "false")

  try {
    const response = await fetch(emailEndpoint, {
      method: "POST",
      body: payload,
    })

    if (response.ok) {
      showThankYou.value = true
      Object.keys(formData).forEach((k) => (formData[k] = ""))
      Object.keys(errors).forEach((k) => delete errors[k])
    } else {
      alert("There was a problem submitting the form.")
    }
  } catch (err) {
    console.error("Form submission error:", err)
  } finally {
    submitting.value = false
  }
}

/* ------------------------
   GSAP
------------------------ */
let ctx

onMounted(() => {
  if (!process.client) return

  ctx = gsap.context(() => {
    const heading = document.querySelector(".heading")
    const subheading = document.querySelector(".subheading")
    const button = document.querySelector(".btn-animate")

    if (heading) {
      gsap.fromTo(
        heading,
        { opacity: 0, y: -150 },
        {
          opacity: 1,
          y: 0,
          duration: 1,
          ease: "power1.in",
          scrollTrigger: {
            trigger: heading,
            start: "top 80%",
          },
        }
      )
    }

    if (subheading) {
      gsap.fromTo(
        subheading,
        { opacity: 0, x: -150 },
        {
          opacity: 1,
          x: 0,
          duration: 1,
          delay: 0.5,
          ease: "power2.in",
          scrollTrigger: {
            trigger: subheading,
            start: "top 80%",
          },
        }
      )
    }

    if (button) {
      gsap.fromTo(
        button,
        { opacity: 0, y: 50 },
        {
          opacity: 1,
          y: 0,
          duration: 1,
          ease: "power2.in",
          scrollTrigger: {
            trigger: button,
            start: "top 80%",
          },
        }
      )

      const hover = () => {
        gsap.fromTo(
          button,
          { scale: 1 },
          {
            scale: 1.08,
            duration: 0.2,
            yoyo: true,
            repeat: 1,
            ease: "power1.out",
          }
        )
      }

      button.addEventListener("mouseenter", hover)

      onBeforeUnmount(() => {
        button.removeEventListener("mouseenter", hover)
      })
    }
  })
})

onBeforeUnmount(() => {
  ctx?.revert()
})
</script>

<template>
  <div class="relative overflow-hidden">
    <!-- HEADER -->
    <div class="flex flex-col items-center gap-4 bg-blue-600">
      <h2
        class="p-4 font-bold text-slate-50 text-4xl lg:text-6xl text-center heading"
      >
        Have a Question or a Project in Mind?
      </h2>

      <p
        class="p-5 max-w-screen-md text-slate-100 text-xl text-center subheading"
      >
        We'd love to hear from you! Drop us a message and we'll get back to you.
      </p>
    </div>

    <!-- FORM -->
    <div
      id="contact-form"
      class="flex justify-center bg-gradient-to-b from-blue-600 to-blue-950 p-4 md:p-20 w-full"
    >
      <form
        ref="formRef"
        @submit.prevent="handleSubmit"
        class="space-y-6 bg-slate-100 shadow-lg p-6 rounded-lg w-full max-w-screen-md"
      >
        <div>
          <label class="block font-medium text-sky-950">Company</label>
          <input v-model="formData.company" class="input" />
        </div>

        <div>
          <label class="block font-medium text-sky-950">First Name *</label>
          <input v-model="formData.firstName" class="input" />
          <p v-if="errors.firstName" class="error">{{ errors.firstName }}</p>
        </div>

        <div>
          <label class="block font-medium text-sky-950">Last Name *</label>
          <input v-model="formData.lastName" class="input" />
          <p v-if="errors.lastName" class="error">{{ errors.lastName }}</p>
        </div>

        <div>
          <label class="block font-medium text-sky-950">Email *</label>
          <input type="email" v-model="formData.email" class="input" />
          <p v-if="errors.email" class="error">{{ errors.email }}</p>
        </div>

        <div>
          <label class="block font-medium text-sky-950">Message *</label>
          <textarea
            v-model="formData.message"
            :maxlength="maxMessageLength"
            rows="4"
            class="input"
          />
          <div class="text-sm text-right" :class="messageLengthClass">
            {{ formData.message.length }}/{{ maxMessageLength }}
          </div>
          <p v-if="errors.message" class="error">{{ errors.message }}</p>
        </div>

        <button
          type="submit"
          :disabled="submitting"
          class="bg-gradient-to-br from-zinc-800 to-zinc-900 py-3 rounded-full w-full font-semibold text-white text-lg btn-animate"
        >
          {{ submitting ? "Submitting..." : "Submit" }}
        </button>
      </form>
    </div>

    <!-- THANK YOU MODAL -->
    <div
      v-if="showThankYou"
      class="z-50 fixed inset-0 flex justify-center items-center bg-black/50"
    >
      <div class="bg-white shadow-lg p-8 rounded-lg text-center">
        <h2 class="mb-4 font-bold text-green-600 text-2xl">Thank You!</h2>
        <p>Your message has been submitted successfully.</p>
        <button
          class="bg-blue-600 mt-6 px-4 py-2 rounded text-white"
          @click="showThankYou = false"
        >
          Close
        </button>
      </div>
    </div>
  </div>
</template>

<style scoped>
<input
  v-model="formData.firstName"
  class="block mt-1 p-3 border border-gray-300 focus:border-blue-500 rounded-md focus:ring-blue-500 w-full"
/>
</style>
